# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_readme:
    name: "Update README"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
      
      - name: "🕒  Get Current Time"
        uses: gerred/actions/current-time@master
        id: current-time
        
      # Runs a set of commands using the runners shell
      - name: Update README.md
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: |
          sed -i $TIME README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated report"
          git push
